[package]
name = "simple-browser-chooser"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
url = { version = "2" }
fqdn = { version = "0.4" }
log = { version = "0.4" }
flexi_logger = "0.29.5"
